name: ABMCHorse
version: 1.4
api-version: 1.17
main: me.mastergabemod.witherhorse.HorsePlugin
description: Spawn a horse on your location
author: MasterGabeMOD
authors:
  - Akutasan

commands:
  horse:
    description: Mount a horse.
permissions:
  horse.use:
    description: Use /horse